name: Go Lint

on: [push, pull_request]

jobs:
  test:
    name: Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go 1.22.x
      uses: actions/setup-go@v5
      with:
          go-version: 1.22.x
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
