name: Go Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go 1.22
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
      id: go
    - name: Test
      run: go test -v ./...
